name       : terminator
version    : '1.92'
release    : 6
source     :
    - https://github.com/gnome-terminator/terminator/archive/v1.92.tar.gz : 3afac17a63d4d549dd537d46890249982b58527b2387c8d2975607ce8d6f82b2
homepage   : https://gnometerminator.blogspot.com/p/introduction.html
license    : GPL-2.0-only
component  : system.utils
summary    : Store and run multiple GNOME terminals in one window
description: |
    Multiple GNOME terminals in one window.  This is a project to produce an efficient way of filling a large area of screen space with terminals. This is done by splitting the window into a resizeable grid of terminals. As such, you can  produce a very flexible arrangements of terminals for different tasks.
builddeps  :
    - desktop-file-utils
rundeps    :
    - desktop-file-utils
    - gconf
    - keybinder
    - libvte
    - python-configobj
    - python-gobject
    - python-psutil
    - python3-cairo
    - python3-dbus
setup      : |
    %python3_setup
install    : |
    %python3_install
