name       : terminator
version    : 2.1.0
release    : 9
source     :
    - https://github.com/gnome-terminator/terminator/archive/v2.1.0.tar.gz : 5e2e1d33fb5bcc58f0afaca3e0b2aa8a3a24e1e668112c7e0c948828222557ed
homepage   : https://gnometerminator.blogspot.com/p/introduction.html
license    : GPL-2.0-only
component  : system.utils
summary    : Store and run multiple GNOME terminals in one window
description: |
    Multiple GNOME terminals in one window.  This is a project to produce an efficient way of filling a large area of screen space with terminals. This is done by splitting the window into a resizeable grid of terminals. As such, you can  produce a very flexible arrangements of terminals for different tasks.
builddeps  :
    - desktop-file-utils
    - pytest-runner
rundeps    :
    - desktop-file-utils
    - gconf
    - keybinder
    - libvte
    - python-configobj
    - python-gobject
    - python-psutil
    - python3-cairo
    - python3-dbus
setup      : |
    %python3_setup
install    : |
    %python3_install
