name       : terminator
version    : '2.0'
release    : 7
source     :
    - https://github.com/gnome-terminator/terminator/archive/v2.0.tar.gz : 63c3592d977366a068436bd5cc14c1454d6eace5a881179901fc3e6d41df3bc5
homepage   : https://gnometerminator.blogspot.com/p/introduction.html
license    : GPL-2.0-only
component  : system.utils
summary    : Store and run multiple GNOME terminals in one window
description: |
    Multiple GNOME terminals in one window.  This is a project to produce an efficient way of filling a large area of screen space with terminals. This is done by splitting the window into a resizeable grid of terminals. As such, you can  produce a very flexible arrangements of terminals for different tasks.
builddeps  :
    - desktop-file-utils
    - pytest-runner
rundeps    :
    - desktop-file-utils
    - gconf
    - keybinder
    - libvte
    - python-configobj
    - python-gobject
    - python-psutil
    - python3-cairo
    - python3-dbus
setup      : |
    %python3_setup
install    : |
    %python3_install
