name       : terminator
version    : 0.98
release    : 1
source:
  - https://launchpad.net/terminator/trunk/0.98/+download/terminator-0.98.tar.gz : 0a6d8c9ffe36d67e60968fbf2752c521e5d498ceda42ef171ad3e966c02f26c1
license    : GPL-2.0
component  : system.util
summary    : Store and run multiple GNOME terminals in one window
description: |
  Multiple GNOME terminals in one window.  This is a project to produce
  an efficient way of filling a large area of screen space with
  terminals. This is done by splitting the window into a resizeable
  grid of terminals. As such, you can  produce a very flexible
  arrangements of terminals for different tasks.
builddeps  :
  - desktop-file-utils
rundeps    :
  - desktop-file-utils
  - gconf
  - python-gtk2
  - vte2
setup      : |
  %python_setup
install    : |
  %python_install
