name       : terminator
version    : '1.91'
release    : 2
source     :
    - https://launchpad.net/terminator/gtk3/1.91/+download/terminator-1.91.tar.gz : 95f76e3c0253956d19ceab2f8da709a496f1b9cf9b1c5b8d3cd0b6da3cc7be69
license    : GPL-2.0
component  : system.util
summary    : Store and run multiple GNOME terminals in one window
description: |
    Multiple GNOME terminals in one window.  This is a project to produce
    an efficient way of filling a large area of screen space with
    terminals. This is done by splitting the window into a resizeable
    grid of terminals. As such, you can  produce a very flexible
    arrangements of terminals for different tasks.
builddeps  :
    - desktop-file-utils
rundeps    :
    - desktop-file-utils
    - gconf
    - keybinder
    - libvte
    - python-cairo
    - python-dbus
    - python-gobject
    - python-psutil
setup      : |
    %python_setup
install    : |
    %python_install
